apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-web-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-web-app
  template:
    metadata:
      labels:
        app: calculator-web-app
    spec:
      containers:
        - name: calculator-web-app-container
          image: johnsappdev/calculator-web-app.war:latest
          ports:
            - containerPort: 8080