apiVersion: v1
kind: Service
metadata:
  name: calculator-web-app-service
spec:
  selector:
    app: calculator-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort